### ISSUE TITLE
北京联通使用脚本，检测全过，但进iptv卡在正在进行epg连接。

### ISSUE THREAD

**Issue by kilng** [phorcys/merlin-BJ-Unicomm-IPTV-scripts#2]
iptv是中兴的b860a

脚本中设置有疑惑的就是net_config中的，VLAN_VENDOR_CLASS="dslforum.org:HUAWEI:STB:EC6108V9U_pub_bjjlt" ，这个不知中兴b860怎么写。

自己写的是VLAN_VENDOR_CLASS="dslforum.org:ZTE:STB:ZXB860A" 

上网正常，现在就是iptv卡在epg正在连接，用iptv设置中的检测也是全过。

路由是r6300v2，梅林是x7.2

**Comment by phorcys** [comment]
卡在EPG，估计是  iptv的 地址段的问题，
路由器上装bootstrap，opkg安装 tcpdump
然后抓包（只看机顶盒的mac）看看访问的地址段
如果有新的，把它加入到configs/custom/_net_config
的
	IPTV_NETS="61.135.110.0/24 210.13.0.0/23 61.135.107.0/24 61.135.88.0/23 210.13.31.0/24"
列表里
