### ISSUE TITLE
跟开发者的所有设备一样，但是不成功，求助

### ISSUE THREAD

**Issue by icase** [phorcys/merlin-BJ-Unicomm-IPTV-scripts#3]
我的机顶盒也是这个型号，光猫也是MA5675，路由是刷了梅林的AC68U（380.63_X7.2），所以我在脚本里需要改动的只是盒子的MAC地址和路由的LAN IP，其他的我都没动，jffs里目录的权限是777，我没改成775.但最后盒子连接无线以后依然不成功，查看了下vlan的分配，跟service-start脚本里的不一样，如下：

VLANs: BCM5301x enabled mac_check mac_hash
   1: vlan1: 1 2 3 4 5t
   2: vlan2: 0 5
  56: vlan56: 0 5t
  57: vlan57: 0 1 5t 7
  58: vlan58: 1t 4t 7 8t
  59: vlan59: 0t 1t 2 5t 7t
  60: vlan60: 0t 4 5
  61: vlan61: 0t 1 2t 4 7t
  62: vlan62: 0 5t 7t 8t
3961: vlan3961: 0t 5t

测试了盒子的网络一键检测，前三项通过了，后面全部无法通过。

还请帮忙

**Comment by phorcys** [comment]
AC68U的端口和R6300V2不同啊，wan口一个是8一个是5

scripts/service-start 你要自己修改一下
r6300v2是 robocfg vlans reset vlan 1 ports "0 1 2 3 5" vlan 2 port "4 5" vlan 3961 ports "4t 5t" vlan 3964 ports "4t 5t"


我估计AC68U需要改成
robocfg vlans reset vlan 1 ports "0 1 2 3 8" vlan 2 port "4 8" vlan 3961 ports "4t 8t" vlan 3964 ports "4t 8t"

**Comment by icase** [comment]
好的。多谢 @phorcys 的回复，我稍后试试看，不行再继续请教！

**Comment by icase** [comment]
@phorcys 默认的AC68U输入robocfg show显示的信息如下，这样能否最终确定需要改成啥样？

admin@RT-AC68U-2FF0:/tmp/home/root# robocfg show
Switch: enabled 
Port 0: 1000FD enabled stp: none vlan: 2 jumbo: off mac: cc:cc:81:c0:b2:b0
Port 1: 1000FD enabled stp: none vlan: 1 jumbo: off mac: 00:1c:c2:2a:7a:98
Port 2:   DOWN enabled stp: none vlan: 1 jumbo: off mac: 00:00:00:00:00:00
Port 3:   DOWN enabled stp: none vlan: 1 jumbo: off mac: 00:00:00:00:00:00
Port 4:   DOWN enabled stp: none vlan: 1 jumbo: off mac: 00:00:00:00:00:00
Port 8:   DOWN enabled stp: none vlan: 1 jumbo: off mac: 00:00:00:00:00:00
VLANs: BCM5301x enabled mac_check mac_hash
   1: vlan1: 1 2 3 4 5t
   2: vlan2: 0 5t
  56: vlan56: 0 5t
  57: vlan57: 0 1 5t 7
  58: vlan58: 0 1t 4t 7 8t
  59: vlan59: 0t 1t 2 5t 7t
  60: vlan60: 0t 4t 5
  61: vlan61: 0t 1 2t 4t 7t
  62: vlan62: 0 4t 5t 8u

**Comment by icase** [comment]
vlan的端口改了之后，还是没生效，看日志里，服务应该是启动了。我按照你提供的测试命令，每一个的结果都贴在下面，还请麻烦帮忙看下（我把ifconfig信息里的MAC地址在下面粘贴的时候

删掉了）：

**robocfg show**

`ASUSWRT-Merlin RT-AC68U 380.63-X7.2 Fri Nov 11 11:01:59 UTC 2016
admin@RT-AC68U-2FF0:/tmp/home/root# robocfg show
Switch: enabled 
Port 0: 1000FD enabled stp: none vlan: 2 jumbo: off mac: 00:00:00:00:00:00(已隐藏)
Port 1: 1000FD enabled stp: none vlan: 1 jumbo: off mac: 00:00:00:00:00:00(已隐藏)
Port 2:   DOWN enabled stp: none vlan: 1 jumbo: off mac: 00:00:00:00:00:00
Port 3:   DOWN enabled stp: none vlan: 1 jumbo: off mac: 00:00:00:00:00:00
Port 4:   DOWN enabled stp: none vlan: 1 jumbo: off mac: 00:00:00:00:00:00
Port 8:   DOWN enabled stp: none vlan: 2 jumbo: off mac: 00:00:00:00:00:00
VLANs: BCM5301x enabled mac_check mac_hash
   1: vlan1: 1 2 3 4 5t
   2: vlan2: 0 5
  56: vlan56: 0 5t
  57: vlan57: 0 1 5t 7
  58: vlan58: 0 1t 4t 7 8t
  59: vlan59: 0t 1t 2 5t 7t
  60: vlan60: 0t 4t 5
  61: vlan61: 0t 1 2t 4t 7t
  62: vlan62: 0 4t 5t 8u
3961: vlan3961: 0t 5t
`

**ifconfig**
`admin@RT-AC68U-2FF0:/tmp/home/root# ifconfig
br0        Link encap:Ethernet  HWaddr  
           inet addr:192.168.2.1  Bcast:192.168.2.255  Mask:255.255.255.0
           UP BROADCAST RUNNING ALLMULTI MULTICAST  MTU:1500  Metric:1
           RX packets:84090 errors:0 dropped:0 overruns:0 frame:0
           TX packets:83242 errors:0 dropped:0 overruns:0 carrier:0
           collisions:0 txqueuelen:0 
           RX bytes:16875084 (16.0 MiB)  TX bytes:9250445 (8.8 MiB)

eth0       Link encap:Ethernet  HWaddr   
           UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
           RX packets:5468 errors:0 dropped:0 overruns:0 frame:0
           TX packets:6153 errors:0 dropped:0 overruns:0 carrier:0
           collisions:0 txqueuelen:1000 
           RX bytes:1884232 (1.7 MiB)  TX bytes:1444502 (1.3 MiB)
           Interrupt:179 Base address:0x4000 

eth1       Link encap:Ethernet  HWaddr  
           UP BROADCAST RUNNING ALLMULTI MULTICAST  MTU:1500  Metric:1
           RX packets:1252 errors:0 dropped:0 overruns:0 frame:564
           TX packets:1980 errors:2 dropped:0 overruns:0 carrier:0
           collisions:0 txqueuelen:1000 
           RX bytes:522508 (510.2 KiB)  TX bytes:478219 (467.0 KiB)
           Interrupt:163 

eth2       Link encap:Ethernet  HWaddr  
           UP BROADCAST RUNNING ALLMULTI MULTICAST  MTU:1500  Metric:1
           RX packets:84508 errors:0 dropped:0 overruns:0 frame:8979
           TX packets:86020 errors:3 dropped:0 overruns:0 carrier:0
           collisions:0 txqueuelen:1000 
           RX bytes:18109632 (17.2 MiB)  TX bytes:11044089 (10.5 MiB)
           Interrupt:169 

lo         Link encap:Local Loopback  
           inet addr:127.0.0.1  Mask:255.0.0.0
           UP LOOPBACK RUNNING MULTICAST  MTU:16436  Metric:1
           RX packets:2444 errors:0 dropped:0 overruns:0 frame:0
           TX packets:2444 errors:0 dropped:0 overruns:0 carrier:0
           collisions:0 txqueuelen:0 
           RX bytes:499275 (487.5 KiB)  TX bytes:499275 (487.5 KiB)

ppp0       Link encap:Point-to-Point Protocol  
           inet addr:111.201.*.*  P-t-P:111.201.144.1  Mask:255.255.255.255
           UP POINTOPOINT RUNNING MULTICAST  MTU:1492  Metric:1
           RX packets:4903 errors:0 dropped:0 overruns:0 frame:0
           TX packets:4415 errors:0 dropped:0 overruns:0 carrier:0
           collisions:0 txqueuelen:3 
           RX bytes:1599421 (1.5 MiB)  TX bytes:1067075 (1.0 MiB)

vlan1      Link encap:Ethernet  HWaddr  
           UP BROADCAST RUNNING ALLMULTI MULTICAST  MTU:1500  Metric:1
           RX packets:546 errors:0 dropped:0 overruns:0 frame:0
           TX packets:1705 errors:0 dropped:0 overruns:0 carrier:0
           collisions:0 txqueuelen:0 
           RX bytes:190455 (185.9 KiB)  TX bytes:321490 (313.9 KiB)

vlan3961   Link encap:Ethernet  HWaddr   
           inet addr:169.254.77.61  Bcast:169.254.255.255  Mask:255.255.0.0
           UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
           RX packets:1546 errors:0 dropped:0 overruns:0 frame:0
           TX packets:1671 errors:0 dropped:0 overruns:0 carrier:0
           collisions:0 txqueuelen:0 
           RX bytes:445786 (435.3 KiB)  TX bytes:276708 (270.2 KiB)

wl0.1      Link encap:Ethernet  HWaddr   
           UP BROADCAST RUNNING ALLMULTI MULTICAST  MTU:1500  Metric:1
           RX packets:0 errors:0 dropped:0 overruns:0 frame:564
           TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
           collisions:0 txqueuelen:1000 
           RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
`

**cat /tmp/syslog.log**
`部分日志，可能找的不太准，内容太多，见附件`
[syslog.txt](https://github.com/phorcys/merlin-BJ-Unicomm-IPTV-scripts/files/763146/syslog.txt)

**ps**
`admin@RT-AC68U-2FF0:/tmp/home/root# ps
  PID USER       VSZ STAT COMMAND
    1 admin     6220 S    /sbin/preinit
    2 admin        0 SW   [kthreadd]
    3 admin        0 SW   [ksoftirqd/0]
    4 admin        0 SW   [kworker/0:0]
    5 admin        0 SW   [kworker/u:0]
    6 admin        0 SW   [migration/0]
    7 admin        0 SW   [migration/1]
    8 admin        0 SW   [kworker/1:0]
    9 admin        0 SW   [ksoftirqd/1]
   10 admin        0 SW<  [khelper]
   11 admin        0 SW   [kworker/u:1]
   57 admin        0 SW   [sync_supers]
   59 admin        0 SW   [bdi-default]
   60 admin        0 SW<  [kblockd]
  114 admin        0 SW   [kswapd0]
  160 admin        0 SW   [fsnotify_mark]
  168 admin        0 SW<  [crypto]
  240 admin        0 SW   [mtdblock0]
  245 admin        0 SW   [mtdblock1]
  250 admin        0 SW   [mtdblock2]
  255 admin        0 SW   [mtdblock3]
  281 admin        0 SW   [kworker/0:1]
  282 admin        0 SW   [kworker/1:1]
  285 admin        0 SW   [mtdblock4]
  290 admin        0 SW   [mtdblock5]
  294 admin      664 S    hotplug2 --persistent --no-coldplug
  342 admin     6196 S    console
  344 admin     1388 S    /bin/sh
  349 admin        0 SWN  [jffs2_gcd_mtd4]
  386 admin     1380 S    /sbin/syslogd -m 0 -S -O /tmp/syslog.log -s 256 -l 7
  388 admin     1384 S    /sbin/klogd -c 5
  484 admin     6204 S    /sbin/wanduck
  486 admin     1380 S    telnetd -b 192.168.2.1
  489 admin     1244 S    /usr/bin/skipd
  490 admin     1068 S    dropbear -p 22 -a -a
  492 admin     1184 S    /bin/eapd
  494 admin     1784 S    /bin/wps_monitor
  495 admin     6204 S    wpsaide
  496 admin     1824 S    nas
  498 admin     1272 S    /usr/sbin/acsd
  555 admin     6376 S    httpds -s -p 9528 -i br0
  556 admin     6316 S    httpd -i br0
  558 admin     1392 S    crond
  559 admin     1156 S    /usr/sbin/infosvr br0
  561 admin     6204 S    watchdog
  565 admin     2284 S    rstats
  568 admin     6204 S    ots
  575 admin     1200 S    lld2d br0
  578 admin     1528 S    networkmap --bootwait
  580 admin     6204 S    bwdpi_check
  581 admin     6204 S    hour_monitor
  633 admin     1380 S    /sbin/zcip -p /var/run/zcip0.pid vlan3961 /tmp/zcip
  634 admin     1388 S    /usr/sbin/pppd file /tmp/ppp/options.wan0
  646 admin        0 SW   [khubd]
  759 admin     6204 S    usbled
  760 admin     2208 S    u2ec
  761 admin     1228 S    lpd br0
  764 admin        0 SW   [scsi_eh_0]
  765 admin        0 SW   [usb-storage]
  771 admin     2208 S    u2ec
  772 admin     2208 S    u2ec
  796 admin        0 SW   [jbd2/sda1-8]
  797 admin        0 SW<  [ext4-dio-unwrit]
  851 admin     2000 S    avahi-daemon: running [RT-AC68U-2FF0.local]
  852 admin        0 SW   [flush-mtd-unmap]
  854 admin        0 SW   [flush-8:0]
  868 admin     5348 S    nmbd -D -s /etc/smb.conf
  869 admin     5548 S    /usr/sbin/smbd -D -s /etc/smb.conf
 1098 admin     1096 S    dropbear -p 22 -a -a
 1161 admin     6204 S    ntp
 1590 admin     1392 S    -sh
 1816 admin     1880 S    ss-local -b 0.0.0.0 -l 23456 -c /koolshare/ss/ss.json -u -f /var/run/sslocal1.pid
 1817 admin      844 S    miniupnpd -f /etc/upnp/config
 1823 admin      848 S    dns2socks 127.0.0.1 23456 8.8.8.8 53 127.0.0.1 7913
 1841 admin      848 S    dns2socks 127.0.0.1 23456 8.8.8.8 53 127.0.0.1 7913
 1843 admin      848 S    dns2socks 127.0.0.1 23456 8.8.8.8 53 127.0.0.1 7913
 1849 admin     1908 S    ss-redir -b 0.0.0.0 -c /koolshare/ss/ss.json -u -f /var/run/shadowsocks.pid
 1857 admin     6204 S    disk_monitor
 1877 admin     2724 S    wred -B
 1882 admin     2724 S    wred -B
 1883 admin     2724 S    wred -B
 1890 admin     2724 S    wred -B
 1891 admin     2724 S    wred -B
 1892 admin     2724 S    wred -B
 1893 admin     2724 S    wred -B
 1894 admin     2724 S    wred -B
 1895 admin     2724 S    wred -B
 1896 admin     2724 S    wred -B
 1897 admin     2724 S    wred -B
 1935 admin     3676 S    data_colld -i 1800 -p 43200 -b -w /tmp/bwdpi/dc/
 1936 admin     3676 S    data_colld -i 1800 -p 43200 -b -w /tmp/bwdpi/dc/
 1937 admin     3676 S    data_colld -i 1800 -p 43200 -b -w /tmp/bwdpi/dc/
 1938 admin     3676 S    data_colld -i 1800 -p 43200 -b -w /tmp/bwdpi/dc/
 1939 admin     3676 S    data_colld -i 1800 -p 43200 -b -w /tmp/bwdpi/dc/
 1940 admin     3676 S    data_colld -i 1800 -p 43200 -b -w /tmp/bwdpi/dc/
 1962 admin     6204 S    bwdpi_wred_alive
 1977 admin     3676 S    data_colld -i 1800 -p 43200 -b -w /tmp/bwdpi/dc/
 2214 nobody    2776 S    dnsmasq --log-async
 2346 nobody     632 S    /koolshare/shellinabox/shellinaboxd --css=/koolshare/shellinabox/white-on-black.css -b
 2348 nobody     632 S    /koolshare/shellinabox/shellinaboxd --css=/koolshare/shellinabox/white-on-black.css -b
 2385 admin     1068 S    perpboot -d
 2387 admin     1080 S    tinylog -k 3 -s 50000 -t /var/log/perpd
 2388 admin     1212 S    perpd -a 6 /koolshare/perp
 2512 admin     1136 S    dropbear -p 22 -a -a
 2513 admin     1400 S    -sh
 2880 admin     1384 R    ps
`
[syslog.txt](https://github.com/phorcys/merlin-BJ-Unicomm-IPTV-scripts/files/763149/syslog.txt)

**Comment by phorcys** [comment]
检查一下 /jffs/scripts/services-start  的权限
看起来这个脚本没有成功运行

**Comment by icase** [comment]
权限设置的是777，这个还有问题么？

**Comment by phorcys** [comment]
似乎是services-start没有正确运行，检查一下吧
权限应该是755
看看文件名之类是否完全正确，检查一下这个脚本为什么没有正常运行
