### ISSUE TITLE
使用ac66u-b1运行脚本时会停在wan-start

### ISSUE THREAD

**Issue by samuelszhang** [phorcys/merlin-BJ-Unicomm-IPTV-scripts#4]
手动sh -x wan-start结果如下：
602@RT-AC66U_B1-53E8:/jffs/scripts# sh -x wan-start 
+ logger wan-start event called with args: 
+ source /jffs/scripts/custom/_net_functions
+ init_config
+ local config_file=/jffs/configs/custom/_net_config
+ [ ! -f /jffs/configs/custom/_net_config ]
+ source /jffs/configs/custom/_net_config
+ CUSTOM_CONFIG_DIR=/jffs/configs/custom
+ CUSTOM_SCRIPT_DIR=/jffs/scripts/custom
+ LAN_NET=192.168.1.0/24
+ nvram get lan_ipaddr
+ LAN_IP=192.168.1.1
+ nvram get wl0_ifname
+ LAN_IFACE=eth1
+ nvram get wl1_ifname
+ WLAN_IFACE=eth2
+ nvram get lan_ifname
+ LAN_BR=br0
+ VLAN_IFACE=vlan3964
+ VLAN_VENDOR_CLASS=dslforum.org:HUAWEI:STB:EC6108V9U_pub_bjjlt
+ VLAN_IP_FILE=/tmp/vlan_ip
+ IPTV_NETS=61.135.110.0/24 210.13.0.0/23 61.135.107.0/24 61.135.88.0/23 210.13.31.0/24
+ IPTV_BOX_MACS=54:93:59:ee:d7:55
+ [ -f /tmp/vlan_ip ]
+ configure_vlan
+ local script=/jffs/scripts/custom/post-dhcp-vlan-config
+ [ -f /jffs/scripts/custom/post-dhcp-vlan-config ]
+ logger wan-start: kicking off vlan config
+ logger wan-start: udhcpc -i vlan3964 -p /var/run/udhcpc0.pid -V dslforum.org:HUAWEI:STB:EC6108V9U_pub_bjjlt -s /jffs/scripts/custom/post-dhcp-vlan-config 
+ local_command udhcpc udhcpc -i vlan3964 -p /var/run/udhcpc0.pid -V dslforum.org:HUAWEI:STB:EC6108V9U_pub_bjjlt -s /jffs/scripts/custom/post-dhcp-vlan-config
+ local description=udhcpc
+ shift
+ logger udhcpc: running command: udhcpc -i vlan3964 -p /var/run/udhcpc0.pid -V dslforum.org:HUAWEI:STB:EC6108V9U_pub_bjjlt -s /jffs/scripts/custom/post-dhcp-vlan-config
+ udhcpc -i vlan3964 -p /var/run/udhcpc0.pid -V dslforum.org:HUAWEI:STB:EC6108V9U_pub_bjjlt -s /jffs/scripts/custom/post-dhcp-vlan-config

另外请帮忙看一下VLAN的配置是不是有问题，目前vlan3961/3964都不能获取IP

Switch: enabled 
Port 0:  100FD enabled stp: none vlan: 1 jumbo: off mac: cc:cc:81:c0:96:bb
Port 1: 1000FD enabled stp: none vlan: 1 jumbo: off mac: e8:bb:3d:33:8b:60
Port 2:   DOWN enabled stp: none vlan: 1 jumbo: off mac: 00:00:00:00:00:00
Port 3: 1000FD enabled stp: none vlan: 1 jumbo: off mac: 00:11:32:3f:f3:e3
Port 4:   DOWN enabled stp: none vlan: 1 jumbo: off mac: 00:00:00:00:00:00
Port 8:   DOWN enabled stp: none vlan: 2 jumbo: off mac: 00:00:00:00:00:00
VLANs: BCM5301x enabled mac_check mac_hash
   1: vlan1: 0 1 2 3 8u
3961: vlan3961: 0t 8t
3964: vlan3964: 0t 8t

**Comment by phorcys** [comment]
先在光猫上确认一下是不是正确设置了VLAN绑定
以及光猫默认vlan是否正确

其次确认一下路由器 cpu 口lan口  vlan  id
（未安装脚本时候，路由器启动后，robocfg show)
对应的修改services-start脚本里的vlan   id
