### ISSUE TITLE
跟开发者的一样，现在iptv只能点播，无法直播

### ISSUE THREAD

**Issue by kaisaintz** [phorcys/merlin-BJ-Unicomm-IPTV-scripts#5]
按照开发者的配置，目前iptv点播没问题了，但是无法直播，直播黑屏，如果将iptv盒子的线直连光猫的lan4，直播是没问题的

**Comment by phorcys** [comment]
无法直播 = igmp proxy没有正常工作，
保证你的 本地网络 IPTV 里，开启 "启动组播路由 (IGMP Proxy)" 和 "开启高效组播转发 (IGMP Snooping )"两项
保证你的 光猫有 3961 和3964 两组映射，还不行可以加一组 4000:4000映射
检查 firewall-start是否正确执行

校验你的iptv 组播端口是不是和firewall-start里的组播端口配置一致

**Comment by hzy0110** [comment]
ifconfig 的 VLAN 里拿不到是什么原因啊？

**Comment by phorcys** [comment]
vlan id不对
光猫设置错误
脚本没有正确执行
路由器vlan划分错误

可能性太多了，自己检查日志吧
