### ISSUE TITLE
wan-start line 33 lost $

### ISSUE THREAD

**Issue by yanyuqin** [phorcys/merlin-BJ-Unicomm-IPTV-scripts#6]
wan-start line 33 lost $

 'snooper' "snooper -b br0 -s VLAN_IFACE"

**Comment by phorcys** [comment]
Thanks for the fix
 fixed  by commit [f19ff21bac4d85bdc062f814a3119543ca7ab514](https://github.com/phorcys/merlin-BJ-Unicomm-IPTV-scripts/commit/f19ff21bac4d85bdc062f814a3119543ca7ab514)
