### ISSUE TITLE
是不是必须要知道猫的 VLAN 情况？

### ISSUE THREAD

**Issue by wd** [phorcys/merlin-BJ-Unicomm-IPTV-scripts#8]
> 单网线连接光猫LAN1 <-> 路由器Wan
> 光猫支持 VLAN绑定（大部分都支持，不过需要 管理员/root 权限)
> 光猫internet和iptv链接都设置为桥接模式，记录internet和 iptv的vlanid （我这里使用 3961,3964)
> 光猫 路由-> Vlan绑定 设置 光猫LAN1为 VLAN绑定模式 ，映射关系为: 3961/3961;3964/3964
> 路由器梅林固件，本地网络 IPTV 里，设置 “选择 ISP 设置档” 为手动模式，互联网VID填入 internet的vlanid（例如 3961） 并开启 "启动组播路由 (IGMP Proxy)" 和 "开启高效组播转发 (IGMP Snooping )"两项
> 路由器启用 jffs

看了前置条件，如果我没法看和修改光猫的 vlan 情况，是不是基本就没戏了？
我这猫是 FireHome AN5006-04

**Comment by phorcys** [comment]
拿不到光猫的VLAN信息，就没法搞了

**Comment by wd** [comment]
好的。我目前用了另外一个方法，多加了一个路由器，然后 lan 和上网的路由器的 lan 接一起，通过那个路由器看 iptv，不影响上网。也还可以。
